version: '3'

services:
  jenkins:
    image: jenkins/jenkins:lts
    container_name: jenkins
    ports:
      - "8081:8080"
      - "50000:50000"
    volumes:
      - ./data:/var/jenkins_home
      - ./allure-results:/var/jenkins_home/workspace/allure-results
    networks:
      - ci_network

  allure:
    image: frankescobar/allure-docker-service
    container_name: allure
    ports:
      - "5050:5050"
    volumes:
      - ./allure-results:/app/allure-results
    networks:
      - ci_network

volumes:
  jenkins_home:

networks:
  ci_network:
    driver: bridge
